name: Build Kernel on ubuntu 22.04
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - uses: actions/checkout@v3
    - name: Prepare Configuration
      run: |
        echo 1
    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build-kernel-${{ env.DEVICE }}${{ env.UPLOADNAME }}
        max-size: 2G

    - name: Build kernel
      run: |
        sudo sh run.sh
        cd out/arch/arm64/boot/
        ls
        cd $GITHUB_WORKSPACE
        echo 2
        cd arch/arm64/boot/
        ls
        cd $GITHUB_WORKSPACE
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: 1
        path: out/arch/arm64/boot/install.sh